<a href="https://colab.research.google.com/github/tecXworld/Natural-Language-Processing/blob/main/Embedding_layer.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
voc_size=10000

In [5]:
onehot_repr=[one_hot(words,voc_size)for words in sent] 
print(onehot_repr)

[[9870, 4669, 9999, 2720], [9870, 4669, 9999, 6402], [9870, 8110, 9999, 6056], [7157, 2118, 9699, 350, 595], [7157, 2118, 9699, 350, 6704], [1318, 9870, 9866, 9999, 1671], [5795, 180, 7468, 350]]


In [6]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [7]:
import numpy as np

In [8]:
sent_length=8
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 9870 4669 9999 2720]
 [   0    0    0    0 9870 4669 9999 6402]
 [   0    0    0    0 9870 8110 9999 6056]
 [   0    0    0 7157 2118 9699  350  595]
 [   0    0    0 7157 2118 9699  350 6704]
 [   0    0    0 1318 9870 9866 9999 1671]
 [   0    0    0    0 5795  180 7468  350]]


In [9]:
dim=10

In [10]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

In [11]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, 8, 10)             100000    
Total params: 100,000
Trainable params: 100,000
Non-trainable params: 0
_________________________________________________________________


In [12]:
print(model.predict(embedded_docs))

[[[-0.01448864  0.00328451 -0.00995637 -0.03207143 -0.04786589
   -0.03700016 -0.03129331  0.04367996 -0.03130828 -0.04635489]
  [-0.01448864  0.00328451 -0.00995637 -0.03207143 -0.04786589
   -0.03700016 -0.03129331  0.04367996 -0.03130828 -0.04635489]
  [-0.01448864  0.00328451 -0.00995637 -0.03207143 -0.04786589
   -0.03700016 -0.03129331  0.04367996 -0.03130828 -0.04635489]
  [-0.01448864  0.00328451 -0.00995637 -0.03207143 -0.04786589
   -0.03700016 -0.03129331  0.04367996 -0.03130828 -0.04635489]
  [-0.01961914  0.01403136 -0.03570136  0.0334427  -0.00150607
    0.01092855  0.00965739  0.0318826  -0.0220849  -0.02799405]
  [ 0.00099768 -0.00490699  0.03971722  0.01541281  0.01541922
    0.02308539  0.02848256  0.02299568  0.02131077  0.02536762]
  [ 0.02777263 -0.02538402  0.02577019  0.01898432 -0.04636415
   -0.01742635  0.03409096  0.03805364 -0.0252031  -0.00410389]
  [ 0.03485069  0.02149079  0.01241083 -0.00522793 -0.03651117
    0.00180287  0.04469658 -0.01503301  0.000623

In [13]:
embedded_docs[0]

array([   0,    0,    0,    0, 9870, 4669, 9999, 2720], dtype=int32)

In [14]:
print(model.predict(embedded_docs)[0])

[[-0.01448864  0.00328451 -0.00995637 -0.03207143 -0.04786589 -0.03700016
  -0.03129331  0.04367996 -0.03130828 -0.04635489]
 [-0.01448864  0.00328451 -0.00995637 -0.03207143 -0.04786589 -0.03700016
  -0.03129331  0.04367996 -0.03130828 -0.04635489]
 [-0.01448864  0.00328451 -0.00995637 -0.03207143 -0.04786589 -0.03700016
  -0.03129331  0.04367996 -0.03130828 -0.04635489]
 [-0.01448864  0.00328451 -0.00995637 -0.03207143 -0.04786589 -0.03700016
  -0.03129331  0.04367996 -0.03130828 -0.04635489]
 [-0.01961914  0.01403136 -0.03570136  0.0334427  -0.00150607  0.01092855
   0.00965739  0.0318826  -0.0220849  -0.02799405]
 [ 0.00099768 -0.00490699  0.03971722  0.01541281  0.01541922  0.02308539
   0.02848256  0.02299568  0.02131077  0.02536762]
 [ 0.02777263 -0.02538402  0.02577019  0.01898432 -0.04636415 -0.01742635
   0.03409096  0.03805364 -0.0252031  -0.00410389]
 [ 0.03485069  0.02149079  0.01241083 -0.00522793 -0.03651117  0.00180287
   0.04469658 -0.01503301  0.00062306  0.03211557]]